### ISSUE TITLE
Python Error in Payroll / Salary Rules

### ISSUE THREAD

**Issue by t3mschm2d** [Mint-System/Odoo-Wiki#10]
Used version: Odoo Online 17.00

After working through your wiki about salary rules, I came across the error that the shown way of accessing the values of the **inputs** `dict` does not work! [Link to the wiki-page](https://www.odoo-wiki.org/personalabrechnung-eingaben.html)

**Example**

`result = inputs.QUELLEN.amount > 0.0 if inputs.QUELLEN else False`

When creating a payslip using your example above, Odoo throws an error that it can't access the `dict`. This is because you're trying to access a Python dictionary value using dot notation. 

I've changed the code as follows and it works: 

`result = inputs["QUELLEN"].amount > 0.0 if inputs["QUELLEN"] else False`

Sorry for not submitting a PR - I have not had time to do so! Hope you find some time to fix the wiki article.

**Comment by janikvonrotz** [comment]
@t3mschm2d  Danke für den Hinweis. Ich habe mal alle Instanzen von `inputs.KEY` zu `input["KEY"]` geändert.
